configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/channel3%2Fpublic-sdk-6f2bba2b3765e842a82fd3756eebbab250fc655479aba4a10f21a87d9ec62ee5.yml
openapi_spec_hash: 980b93da33ace3e0ae7813b8ca1a2078
config_hash: 0ec132fef7cbcef12aebece85f2ef2b1
