configured_endpoints: 6
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/channel3%2Fpublic-sdk-59890da6d900aeeea62e773addac190fd8cec44cb723011145d089cf9d76bfdf.yml
openapi_spec_hash: 696b40dac0a11ea8c717d6dd6445a2e0
config_hash: 0ec132fef7cbcef12aebece85f2ef2b1
